export const sidebarConfig = [
  {
    key: "dashboard",
    path: "/",
    label: "Dashboard",
    icon: "solar:home-smile-angle-outline",
    exact: true,
  },
  {
    type: "header",
    label: "Application",
  },
  {
    key: "tickets",
    path: "/tickets",
    label: "Customer Support",
    icon: "mdi:ticket-outline",
  },
  {
    key: "users_list",
    path: "/users-list",
    label: "Admin Users",
    icon: "flowbite:users-group-outline",
  },
  {
    key: "website_users",
    path: "/website-users",
    label: "Website Users",
    icon: "mdi:web",
  },
  {
    key: "roles",
    path: "/assign-role",
    label: "Roles",
    icon: "flowbite:users-group-outline",
  },
  {
    key: "permissions",
    path: "/permissions",
    label: "Permissions",
    icon: "mdi:shield-check-outline",
  },
  {
    key: "customize_courses",
    path: "/customize-courses",
    label: "Customize Courses",
    icon: "mdi:cog-outline",
  },
  {
    key: "course_assessments",
    path: "/course-assessments",
    label: "Course Assessments",
    icon: "mdi:clipboard-text-outline",
  },
  {
    key: "course_progress",
    path: "/course-progress",
    label: "Course Progress",
    icon: "ph:chart-bar-bold",
  },
  {
    key: "course_enrollments",
    path: "/course-enrollments",
    label: "Course Enrollments",
    icon: "material-symbols:group",
  },
  {
    key: "assignments",
    path: "/assignments-admin",
    label: "Assignments & Grading",
    icon: "material-symbols:assignment-turned-in-outline",
  },
  {
    key: "jobs",
    path: "/jobs-admin",
    label: "Jobs & Applications",
    icon: "material-symbols:work-outline",
  },
  {
    key: "live_classes",
    path: "/live-class",
    label: "Live Classes",
    icon: "material-symbols:live-tv-outline",
  },

  {
    key: "blogs",
    path: "/blog",
    label: "Blogs",
    icon: "ri-user-settings-line",
  },
  {
    key: "landing_pages",
    path: "/landing-pages",
    label: "Landing Pages",
    icon: "ri-layout-line",
  },
  {
    key: "landing_page_registrations",
    path: "/landing-page-registrations",
    label: "Landing Page Registrations",
    icon: "material-symbols:contact-mail-outline",
  },
  {
    key: "testimonials",
    path: "/testimonials",
    label: "Testimonials",
    icon: "mdi:account-voice",
  },
  {
    key: "expert_videos",
    path: "/expert-videos",
    label: "Expert Videos",
    icon: "mdi:play-box-multiple-outline",
  },
  {
    key: "why_gradus",
    path: "/why-gradus-video",
    label: "Why Gradus Video",
    icon: "mdi:play-network-outline",
  },
  {
    key: "banners",
    path: "/banners",
    label: "Banners",
    icon: "mdi:image-multiple-outline",
  },
  {
    key: "page_meta",
    path: "/page-meta",
    label: "Page Meta",
    icon: "mdi:tag-text-outline",
  },
  {
    key: "partner_logos",
    path: "/partner-logos",
    label: "Partner Logos",
    icon: "mdi:handshake-outline",
  },
  {
    key: "events",
    path: "/events-admin",
    label: "Events",
    icon: "solar:calendar-bold-duotone",
  },
  {
    key: "event_registrations",
    path: "/event-registrations",
    label: "Event Registrations",
    icon: "material-symbols:contact-mail-outline",
  },
  {
    key: "inquiries",
    path: "/inquiries",
    label: "Inquiries",
    icon: "mdi:email-outline",
  },
  {
    key: "callback_requests",
    path: "/callback-requests",
    label: "Call Back Request",
    icon: "mdi:phone-incoming",
  },
  {
    key: "calendar",
    path: "/calendar-main",
    label: "Calendar",
    icon: "solar:calendar-outline",
  },
  {
    type: "header",
    label: "Settings",
  },
  {
    key: "authentication_group",
    label: "Authentication",
    icon: "simple-line-icons:vector",
    children: [
      {
        key: "signin",
        path: "/sign-in",
        label: "Sign In",
        icon: "ri-circle-fill",
        iconColor: "text-primary-600",
      },
      {
        key: "signup",
        path: "/sign-up",
        label: "Sign Up",
        icon: "ri-circle-fill",
        iconColor: "text-warning-main",
      },
      {
        key: "forgot_password",
        path: "/forgot-password",
        label: "Forgot Password",
        icon: "ri-circle-fill",
        iconColor: "text-info-main",
      },
    ],
  },
  {
    key: "gallery_group",
    label: "Gallery",
    icon: "flowbite:users-group-outline",
    children: [
      {
        key: "gallery_grid",
        path: "/gallery-grid",
        label: "Gallery Grid",
        icon: "ri-circle-fill",
        iconColor: "text-primary-600",
      },
      {
        key: "gallery_desc",
        path: "/gallery",
        label: "Gallery Grid Desc",
        icon: "ri-circle-fill",
        iconColor: "text-warning-main",
      },
      {
        key: "gallery_masonry",
        path: "/gallery-masonry",
        label: "Gallery Masonry",
        icon: "ri-circle-fill",
        iconColor: "text-info-main",
      },
      {
        key: "gallery_hover",
        path: "/gallery-hover",
        label: "Gallery Hover Effect",
        icon: "ri-circle-fill",
        iconColor: "text-danger-main",
      },
    ],
  },
  {
    key: "pricing",
    path: "/pricing",
    label: "Pricing",
    icon: "hugeicons:money-send-square",
  },
  {
    key: "faq",
    path: "/faq",
    label: "FAQs",
    icon: "mage:message-question-mark-round",
  },
  {
    key: "error_404",
    path: "/error",
    label: "404",
    icon: "streamline:straight-face",
  },
  {
    key: "terms_condition",
    path: "/terms-condition",
    label: "Terms & Conditions",
    icon: "octicon:info-24",
  },
  {
    key: "coming_soon",
    path: "/coming-soon",
    label: "Coming Soon",
    className: "ri-rocket-line",
  },
  {
    key: "access_denied",
    path: "/access-denied",
    label: "Access Denied",
    className: "ri-folder-lock-line",
  },
  {
    key: "maintenance",
    path: "/maintenance",
    label: "Maintenance",
    className: "ri-hammer-line",
  },
  {
    key: "blank_page",
    path: "/blank-page",
    label: "Blank Page",
    className: "ri-checkbox-multiple-blank-line",
  },
  {
    key: "settings_group",
    label: "Settings",
    icon: "icon-park-outline:setting-two",
    children: [
      {
        key: "company",
        path: "/company",
        label: "Company",
        icon: "ri-circle-fill",
        iconColor: "text-primary-600",
      },
      {
        key: "notification",
        path: "/notification",
        label: "Notification",
        icon: "ri-circle-fill",
        iconColor: "text-warning-main",
      },
      {
        key: "notification_alert",
        path: "/notification-alert",
        label: "Notification Alert",
        icon: "ri-circle-fill",
        iconColor: "text-info-main",
      },
      {
        key: "theme",
        path: "/theme",
        label: "Theme",
        icon: "ri-circle-fill",
        iconColor: "text-danger-main",
      },
      {
        key: "currencies",
        path: "/currencies",
        label: "Currencies",
        icon: "ri-circle-fill",
        iconColor: "text-danger-main",
      },
      {
        key: "languages",
        path: "/language",
        label: "Languages",
        icon: "ri-circle-fill",
        iconColor: "text-danger-main",
      },
      {
        key: "payment_gateway",
        path: "/payment-gateway",
        label: "Payment Gateway",
        icon: "ri-circle-fill",
        iconColor: "text-danger-main",
      },
    ],
  },
];
